# "service" is the name of this project. This will also be added to your AWS resource names.
service: cloud-interaction
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.13
  stage: dev
  region: ap-northeast-2
  profile: backend
  logRetentionInDays: 3
  timeout: 30
  architecture: arm64
  iam:
    role: arn:aws:iam::021889793243:role/open-template-chatbot-dev-ap-northeast-2-lambdaRole
  # deploymentBucket:
  #   name: open-template-chatbot
  #   serverSideEncryption: AES256

  # iam:
  #   # Instruct Serverless to use an existing IAM role for all Lambda functions
  #   role: arn:aws:iam::XXXXXX:role/role
  #   # OR configure the role that will be created by Serverless (simplest):
  #   role:
  #     # Add statements to the IAM role to give permissions to Lambda functions
  #     statements:
  #       - Effect: Allow
  #         Action:
  #           - 's3:ListBucket'
  #         Resource:
  #           Fn::Join:
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - Ref: ServerlessDeploymentBucket

  # apiGateway:
  #   minimumCompressionSize: 1024

package:
  individually: true

plugins:
  - serverless-python-requirements

functions:
  chatbot:
    handler: cloud_interaction.main.handler
    timeout: 30
    memorySize: 128
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
        - "!poetry.lock"
    url: true
    events:
      - httpApi:
          path: /cloud
          method: post
